from typing import List
import datetime

def expand_signatures(signatures: List[str]) -> List[str]:
    while True:
        changed = False

        new_signatures = []

        # Expand signatures into all types.
        for sig in signatures:
            if "m" in sig:
                changed = True
                new_signatures.append(sig.replace("m", "R", 1))
                new_signatures.append(sig.replace("m", "M", 1))
                new_signatures.append(sig.replace("m", "P", 1))
            elif "c" in sig:
                changed = True
                new_signatures.append(sig.replace("c", "C"))
            elif "l" in sig:
                changed = True
                new_signatures.append(sig.replace("l", "L"))
            else:
                new_signatures.append(sig)

        signatures = new_signatures
        if not changed:
            break

    return signatures

class Instruction:
    name: str
    signatures: List[str]
    template: str

    def __init__(self, name: str, signatures: List[str], template: str) -> None:
        self.name = name
        self.signatures = expand_signatures(signatures)
        self.template = template

mv_template = """uint8_t* mem = &$1;
    *mem = $2;"""
mv = Instruction("MV", ["mc", "mm"], mv_template)

inc_template = """++$1;"""
inc = Instruction("INC", ["m"], inc_template)

dec_template = """--$1;"""
dec = Instruction("DEC", ["m"], dec_template)

add_template = """uint8_t* mem = &$1;
    *mem += $2;"""
add = Instruction("ADD", ["mc", "mm"], add_template)

sub_template = """uint8_t* mem = &$1;
    *mem -= $2;"""
sub = Instruction("SUB", ["mc", "mm"], sub_template)

instructions = [mv, inc, dec, add, sub]

def sig_letter_to_macro(letter: str) -> str:
    if letter == "C":
        return "CONST()"
    if letter == "R":
        return "REG()"
    if letter == "M":
        return "MEM()"
    if letter == "P":
        return "PTR()"
    if letter == "L":
        return "CONST()"

    raise ValueError(f"Invalid signature letter '{letter}'.")

def fileCreationDateHeader() -> str:
    return f"""//
// Generated by boilerplateGenerator.py on {datetime.datetime.today().strftime("%d/%m/%Y")}.
//
"""

def printOpcodes(instr: Instruction) -> None:
    for sig in instr.signatures:
        print(f"\tX({instr.name}_{sig}) \\")
    print()

def generate_handlers(instr: Instruction) -> str:
    # Generate handlers.
    result = f"""{fileCreationDateHeader()}
#ifndef KAL_{instr.name}_HANDLERS_INC
#define KAL_{instr.name}_HANDLERS_INC

"""

    for sig in instr.signatures:
        func = f"static void {instr.name}_{sig}Handler(VM* vm)\n{{\n\t"
        func += instr.template
        for i in range(len(sig)):
            func = func.replace(f"${i+1}", sig_letter_to_macro(sig[i]))
        func += "\n}\n\n"

        result += func

    print(f"Successfully generated handlers file for {instr.name.lower()}.")

    return result + "#endif"

def sig_letter_to_sig_digit(letter: str) -> str:
    if letter == "C":
        return "1"
    if letter == "R":
        return "2"
    if letter == "M":
        return "3"
    if letter == "P":
        return "4"
    if letter == "L":
        return "5"

    raise ValueError(f"Invalid signature letter '{letter}'.")

def generate_variants(instr: Instruction) -> str:
    result = f"""{fileCreationDateHeader()}
#ifndef KAL_{instr.name}_VARIANTS_INC
#define KAL_{instr.name}_VARIANTS_INC

static const InstrVariant {instr.name.lower()}Variants[] = {{
"""

    for sig in instr.signatures:
        result += f"\t{{OP_{instr.name}_{sig}, {len(sig) + 1}, 0{''.join([sig_letter_to_sig_digit(letter) for letter in sig])}}},\n"

    print(f"Successfully generated variants file for {instr.name.lower()}.")

    return result + "};\n\n#endif"

def generate_all(instr: Instruction) -> None:
    print()
    printOpcodes(instr)

    with open(f"generated/{instr.name.lower()}Handlers.inc", "w+") as file:
        file.write(generate_handlers(instr))

    with open(f"generated/{instr.name.lower()}Variants.inc", "w+") as file:
        file.write(generate_variants(instr))

    print(f"Successfully generated all files for {instr.name.lower()}.")

for instr in instructions:
    generate_all(instr)