from typing import List
import datetime

def expand_signatures(signatures: List[str]) -> List[str]:
    while True:
        changed = False

        new_signatures = []

        # Expand signatures into all types.
        for sig in signatures:
            if "m" in sig:
                changed = True
                new_signatures.append(sig.replace("m", "R", 1))
                new_signatures.append(sig.replace("m", "M", 1))
                new_signatures.append(sig.replace("m", "P", 1))
            elif "c" in sig:
                changed = True
                new_signatures.append(sig.replace("c", "C"))
            elif "l" in sig:
                changed = True
                new_signatures.append(sig.replace("l", "L"))
            else:
                new_signatures.append(sig)

        signatures = new_signatures
        if not changed:
            break

    return signatures

class Instruction:
    name: str
    signatures: List[str]
    template: str

    def __init__(self, name: str, signatures: List[str], template: str) -> None:
        self.name = name
        self.signatures = expand_signatures(signatures)
        self.template = template

def C_op_template(op: str) -> str:
    return f"""uint8_t* mem = &$1;
    *mem {op}= $2;"""

###########################
# Instruction Definitions #
###########################

# A repetitive enough instruction is defined by its name, its signatures (as given in instruction-set.md), and a
# template that defines how it will be executed.

# The template is copy-pasted for each generated opcode, but with $1, $2, and so on being replaces with the first,
# second, and so on operands to that instruction.

# All signatures of an instruction must have the same operand count.

mv = Instruction("MV", ["mc", "mm"], C_op_template(""))

inc_template = """++$1;"""
inc = Instruction("INC", ["m"], inc_template)

dec_template = """--$1;"""
dec = Instruction("DEC", ["m"], dec_template)

add = Instruction("ADD", ["mc", "mm"], C_op_template("+"))
sub = Instruction("SUB", ["mc", "mm"], C_op_template("-"))
mul = Instruction("MUL", ["mc", "mm"], C_op_template("*"))
div = Instruction("DIV", ["mc", "mm"], C_op_template("/"))
and_ = Instruction("AND", ["mc", "mm"], C_op_template("&"))
or_ = Instruction("OR", ["mc", "mm"], C_op_template("|"))
xor = Instruction("XOR", ["mc", "mm"], C_op_template("^"))

not_template = """uint8_t* mem = &$1;
    *mem = !$2;"""
not_ = Instruction("NOT", ["mc", "mm"], not_template)

instructions = [mv, inc, dec, add, sub, mul, div, and_, or_, xor, not_]

###########################
# Instruction Definitions #
###########################

def sig_letter_to_macro(letter: str) -> str:
    if letter == "C":
        return "CONST()"
    if letter == "R":
        return "REG()"
    if letter == "M":
        return "MEM()"
    if letter == "P":
        return "PTR()"
    if letter == "L":
        return "CONST()"

    raise ValueError(f"Invalid signature letter '{letter}'.")

def fileCreationDateHeader() -> str:
    return f"""//
// Generated by boilerplateGenerator.py on {datetime.datetime.today().strftime("%d/%m/%Y")}.
//
"""

def generate_handlers(instr: Instruction) -> None:
    # Generate handlers.
    result = f"""{fileCreationDateHeader()}
#ifndef KAL_{instr.name}_HANDLERS_H
#define KAL_{instr.name}_HANDLERS_H

"""

    for sig in instr.signatures:
        func = f"static void {instr.name}_{sig}Handler(VM* vm)\n{{\n\t"
        func += instr.template
        for i in range(len(sig)):
            func = func.replace(f"${i+1}", sig_letter_to_macro(sig[i]))
        func += "\n}\n\n"

        result += func

    result += "#endif"

    print(f"Successfully generated handlers file for {instr.name.lower()}.")

    with open(f"generated/per-instruction/{instr.name.lower()}Handlers.h", "w+") as file:
         file.write(result)

def generate_handlers_file(instructions: List[Instruction]) -> None:
    for instr in instructions:
        generate_handlers(instr)

    file_contents = f"""{fileCreationDateHeader()}
#ifndef KAL_GENERATED_HANDLERS_H
#define KAL_GENERATED_HANDLERS_H

"""

    for instr in instructions:
        file_contents += f'#include "generated/per-instruction/{instr.name.lower()}Handlers.h"\n'

    file_contents += "\n#endif"

    with open("generated/generatedHandlers.h", "w+") as file:
        file.write(file_contents)

    print("\nSuccessfully created combined handlers file.\n")

def sig_letter_to_sig_digit(letter: str) -> str:
    if letter == "C":
        return "1"
    if letter == "R":
        return "2"
    if letter == "M":
        return "3"
    if letter == "P":
        return "4"
    if letter == "L":
        return "5"

    raise ValueError(f"Invalid signature letter '{letter}'.")

def generate_variants(instr: Instruction) -> None:
    result = f"""{fileCreationDateHeader()}
#ifndef KAL_{instr.name}_VARIANTS_H
#define KAL_{instr.name}_VARIANTS_H

static const InstrVariant {instr.name.lower()}Variants[] = {{
"""

    for sig in instr.signatures:
        result += f"\t{{OP_{instr.name}_{sig}, {len(sig) + 1}, 0{''.join([sig_letter_to_sig_digit(letter) for letter in sig])}}},\n"

    result += "};\n\n#endif"

    print(f"Successfully generated variants file for {instr.name.lower()}.")

    with open(f"generated/per-instruction/{instr.name.lower()}Variants.h", "w+") as file:
        file.write(result)

def generate_variants_file(instructions: List[Instruction]) -> None:
    for instr in instructions:
        generate_variants(instr)

    file_contents = f"""{fileCreationDateHeader()}
#ifndef KAL_GENERATED_VARIANTS_H
#define KAL_GENERATED_VARIANTS_H

"""

    for instr in instructions:
        file_contents += f'#include "generated/per-instruction/{instr.name.lower()}Variants.h"\n'

    file_contents += "\n#endif"

    with open("generated/generatedVariants.h", "w+") as file:
        file.write(file_contents)

    print("\nSuccessfully created combined variants file.\n")

def generate_opcodes(instructions: List[Instruction]) -> None:
    result = f"""{fileCreationDateHeader()}
#ifndef KAL_GENERATED_OPCODES_H
#define KAL_GENERATED_OPCODES_H

#define GENERATED_OPCODES_X \\
"""

    for instr in instructions:
        for sig in instr.signatures:
            result += f"\tX({instr.name}_{sig}) \\\n"

    result += "\n#endif"

    with open("generated/generatedOpcodes.h", "w+") as file:
        file.write(result)

    print("\nSuccessfully created opcodes file.")

def generate_mnemonic_tokens(instructions: List[Instruction]) -> None:
    result = f"""{fileCreationDateHeader()}
#ifndef KAL_GENERATED_MNEMONIC_TOKENS_H
#define KAL_GENERATED_MNEMONIC_TOKENS_H

#define GENERATED_MNEMONIC_TOKENS_X \\
"""

    for instr in instructions:
        result += f"\tX({instr.name}) \\\n"

    result += "\n#endif"

    with open("generated/generatedMnemonicTokens.h", "w+") as file:
        file.write(result)

    print("\nSuccessfully created mnemonic tokens file.")
    
def generate_table_entries(instructions: List[Instruction]) -> None:
    result = f"""{fileCreationDateHeader()}
#ifndef KAL_GENERATED_TABLE_ENTRIES_H
#define KAL_GENERATED_TABLE_ENTRIES_H

#define GENERATED_TABLE_ENTRIES \\
"""

    for instr in instructions:
        result += f"\tTABLE_ENTRY({instr.name}, {instr.name.lower()}, {len(instr.signatures[0])}) \\\n"

    result += "\n#endif"

    with open("generated/generatedTableEntries.h", "w+") as file:
        file.write(result)

    print("\nSuccessfully created table entries file.")

generate_handlers_file(instructions)
generate_variants_file(instructions)
generate_opcodes(instructions)
generate_mnemonic_tokens(instructions)
generate_table_entries(instructions)